# Generated by Django 6.0.2 on 2026-03-05 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_category'),
        ('docs', '0002_alter_usercategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='docs.usercategory'),
            preserve_default=False,
        ),
    ]
