# Generated by Django 6.0.2 on 2026-02-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercategory',
            options={'verbose_name': 'User category', 'verbose_name_plural': 'User categories'},
        ),
    ]
