# Generated by Django 6.0.2 on 2026-03-05 14:48

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_alter_usercategory_options'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
