# Generated by Django 6.0.2 on 2026-03-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_page_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='categories',
        ),
    ]
